import Administration from "../layouts/Administration"
import "../globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Administration>
          {children}
        </Administration>
      </body>
    </html>
  )
}
